# Generated by Django 5.0.3 on 2024-03-27 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coproprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('telephone', models.CharField(help_text='Format: +1234567890', max_length=20)),
                ('copropriete_gere', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCopro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Syndic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=225)),
                ('prenom', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('copropriete_gere', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Copropriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=100)),
                ('autre_info', models.CharField(max_length=255)),
                ('documentcopro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.documentcopro')),
                ('forkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.syndic')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.CharField(max_length=100)),
                ('autre', models.CharField(max_length=255)),
                ('coproprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coproprietaire')),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.copropriete')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.document')),
            ],
        ),
        migrations.AddField(
            model_name='coproprietaire',
            name='forkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.syndic'),
        ),
    ]
